language: c
script: dpkg-buildpackage -b -us -uc

install:
   - sudo apt-add-repository -y ppa:pippijn/ppa
   - sudo apt-get update
   - sudo apt-get install omake noweb valgrind dh-ocaml menhir camlp4-extra libatdgen-ocaml-dev libcurses-ocaml-dev libfacile-ocaml-dev libbatteries-ocaml-dev libsexplib-camlp4-dev libderiving-ocsigen-ocaml-dev libsha-ocaml-dev liblwt-ocaml-dev
   - sudo sh -c 'cat debian/camlp4-meta.patch >> /usr/lib/ocaml/METAS/META.camlp4'
   - cd ..
   - hg clone https://bitbucket.org/camlspotter/pa_monad_custom
   - cd pa_monad_custom
   - make
   - sudo make findlib-install
   - cd ../deliantra
   - wget https://raw.github.com/pippijn/obuild/master/script/travis-depend?$(date +%s) -O travis-depend
   - chmod +x travis-depend
   - ./travis-depend baselib
   - ./travis-depend mlwidgets
   - ./travis-depend codegen
   - ./travis-depend re2ml
   - ./travis-depend pa_json
   - ./travis-depend pa_unpack

# whitelist
branches:
   only:
      - master
      - /.*\/staging/
